name: cc-builder
base: core24
version: '1.0.0'
summary: cloud-init user-data generator
description: |
  A tool for gathering information about a currently running machine and
  generating a basic cloud-config that can be used as a good starting point for
  re-creating the original machine via cloud-init.

grade: devel
confinement: classic

apps:
  cc-builder:
    environment:
      PYTHONPATH: $SNAP/lib/python3.12/site-packages/
    command: bin/cc-builder

parts:
  cc-builder:
    plugin: python
    source: .
    stage-packages:
      - python3.12-minimal
    build-attributes:
      - enable-patchelf
